name: Docker Build

on: 
  pull_request:
    branches: 
      - master
      - feature/*
      - fix/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile
