name: Nodejs Tests

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - feature/*
      - fix/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run test-with-coverage
      env:
        CI: true
    - name: SonarCloud Configure
      if: github.ref == "master"
      run: |
        PROJECT=$(echo $GITHUB_REPOSITORY | sed "s/^.*\///")
        cat << EOF > ./sonar-project.properties
        sonar.organization=$GITHUB_ACTOR
        sonar.projectKey=$PROJECT
        sonar.sources=./src
        sonar.tests=./test
        sonar.javascript.lcov.reportPaths=./coverage/lcov.info
        EOF
    - name: SonarCloud Scan
      if: github.ref == "master"
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Code Cov Publish
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
